---
- hosts: all
  tasks:
    - name: Ensure /etc/cnosdb directory exists
      file:
        path: /etc/cnosdb
        state: directory
        mode: '755'

    - name: Distribute license
      copy:
        src: ~/license.json
        dest: /etc/cnosdb/license.json


- hosts: cnosdb_meta
  vars_files:
    - vars.yml

  roles:
    - cnosdb_meta

#- hosts: cnosdb
#  vars_files:
#    - vars.yml
#
#  roles:
#    - cnosdb

